[package]
name        = "hologram-openssh"
version     = "1.4.0"
description = "hologram: hardened OpenSSH server"
requires    = [
    "holo>=0.10",
    "openssh",
]

# enable SSH daemon
[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/sshd.service"
target = "/usr/lib/systemd/system/sshd.service"

# extend the default SSH configuration with recommendations from
# https://stribika.github.io/2015/01/04/secure-secure-shell.html
[[file]]
path   = "/usr/share/holo/files/10-openssh/etc/ssh/sshd_config.holoscript"
mode   = "0755"
content = """
    #!/bin/sh
    cat
    cat <<-'EOF'

    # custom settings
    KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256

    Protocol 2
    HostKey /etc/ssh/ssh_host_ed22519_key
    HostKey /etc/ssh/ssh_host_rsa_key

    PasswordAuthentication no
    ChallengeResponseAuthentication no
    PubkeyAuthentication yes

    Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr

    MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-ripemd160-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-ripemd160,umac-128@openssh.com
    EOF
"""

# protect against CVE-2016-0777
[[file]]
path    = "/usr/share/holo/files/10-openssh/etc/ssh/ssh_config.holoscript"
mode    = "0755"
content = """
    #!/bin/sh
    echo 'UseRoaming no'
    cat
"""

# filter weak moduli
[[file]]
path   = "/usr/share/holo/run-scripts/10-openssh-filter-weak-moduli.sh"
mode   = "0755"
content = """
    #!/bin/sh
    awk '$5 > 2000' < /etc/ssh/moduli > /tmp/ssh-moduli
    mv /tmp/ssh-moduli /etc/ssh/moduli
"""

# disable weak host keys by placing invalid symlinks at their location
# (TODO: broken! empty files are unpacked instead! fix with:
#   for file in ssh_host_{,dsa_,ecdsa_}key{,.pub}; do ln -fs $file /etc/ssh/$file; done
# )
[[symlink]]
path   = "/etc/ssh/ssh_host_key"
target = "ssh_host_key"
[[symlink]]
path   = "/etc/ssh/ssh_host_key.pub"
target = "ssh_host_key.pub"
[[symlink]]
path   = "/etc/ssh/ssh_host_dsa_key"
target = "ssh_host_dsa_key"
[[symlink]]
path   = "/etc/ssh/ssh_host_dsa_key.pub"
target = "ssh_host_dsa_key.pub"
[[symlink]]
path   = "/etc/ssh/ssh_host_ecdsa_key"
target = "ssh_host_ecdsa_key"
[[symlink]]
path   = "/etc/ssh/ssh_host_ecdsa_key.pub"
target = "ssh_host_ecdsa_key.pub"
