[package]
name        = "hologram-dev-tools"
version     = "1.0.4"
description = "hologram: compilers and development tools"

requires = [
    "apitrace",
    "arch-install-scripts",
    "automoc4",
    "cmake",
    "cloc",
    "cpanminus",
    "doxygen",
    "gdb",
    "go",
    "holo-build",
    "perl-ipc-system-simple", # required for build_package.pl in this repo
    "perl-term-readkey",      # required for "interactive.singlekey" config of Git
    "pkgbuild-introspection",
    "rust",
    "sloccount",
    "valgrind",
]
