[package]
name        = "holodeck-poghril"
version     = "20160706.1"
description = "holodeck: services on Poghril"

requires = [
    "hologram-base",
    "ferm",
]

################################################################################
# identity

[[file]]
path    = "/etc/hostname"
content = "poghril"

[[file]]
path    = "/etc/profile.d/prettyprompt.sh"
content = """
    export PRETTYPROMPT_COMMONUSER=stefan
    export PRETTYPROMPT_HOSTCOLOR='0;36'
"""

[[file]]
path    = "/usr/share/holo/ssh-keys/stefan/poghril.pub"
content = """
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDAYA5hHcedKygolVOQ2PL+NFRhsHLKjhJf4wBf9RZbldCiPlB//4Zd8eqWcG0momVo8v8wPJNj2/X+Yt8yUGgePP0Ydh2pMukXgS+UgysRteMjM39it5QV7IinlBn+pm8tAHMarwUTDN4fvEfl7dCEZZY+bpehDCKNL0dkLYpYURORAUtTxJluRwPPUdHiExKWY2Obhuk0xvcC8/ElHiNj1FO0RFH1G+gnP9Xey0mKRzUzU8CMpRD69fNhUNsh/vfOEIE1Z18yb/pPfvGtbleh8tYX7dAAo80qcRvun9x0PHbCIXGwD2cZ8ra9AU0kAjwQbBcw/fT3wLOHQBrkbhHFFdb2mJ7ZneYg5/NKHyIzdRPtSmy4ItgIFmiEPnYNbwur/Bq9rIiaBp0pX2QO8gvD6UAe4c5ByyZCVXhneZEdfXXu+8X+B13nly1XUZKOUdGhmAF7ZMZboqbC/kgbqOX+J1inf328yUqFGObfL7kFvoro4LTKT+L9sS59hlcKbvNf3Vdj37T4QORWk/AdyXrKGlejcJTUkVY1pOlp3dv1LVAx2wto/fXv/X4BmeLFoRbLY9fKrz6uTRw9X/l3aD1U+jGFQxyswpUOnGizAIAqKaWM+yKjtfYBVSuZ9msojE+lri/WS6jx6tOca5aRyFeqhcbG6oJYr3M5GQfFYdtczQ== stefan@krikkit
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDF8t7PbrvA3wYF9c9nyrX6sE5AXFbAiaafCZskmZIC7Q1lDGdlaOFQ71CW9L3zSgMhI51OYvA0i02FgGTC3jnu7r80r4d/isKJSCSPPTkSVeoyeQZvGSOu6wBnSmq3YWs3Z4TBUE9RPuWTkrB+GOxPpwsK1l/wFzlbJsWm4oUcCH53br//X1QWWilFORVP5eTJUDGxh94mvpM7SSmospNzpvO1DlpUcMWHwUCu3YWrRpvqI6d74igshX5bObUB7vvtJhT9o1y1g3Oxi8NpPa2L8EgCBKlP27oCIO6pZRQi/g95k4DaPWzATVkAnLy9j4h0vEJ60CEtmHhEXnQrAm4Ihyj8SPjEsHP20ZYSyPcB28d10lkN4R7H7ADZ21M/U3lBKpBsKUnoRNnskrOEgOA7WYYnT0t5QfjXeecikPFgKPUynL3E0D7AquXUdMiBJHouQX/mqBgKdtA5jzZHYXP55MyMBG/T1kh2CFaoMiqaeAeE7c9QoyRxmSnblPo6v55omLJKEsYGJlIW8OReD8YPNBEnv25ZykU1CGoeiDDGZPMOtPs5sIG0oPFmkIPL710F1Q8EPHUM07cCelorRcS5YahEj7AB4gCuNoWoPlo04bi4jsDUFhZ+Kx0zXymipp4P6fVWPiCT79DOFdqc8dcuqlIU4gmByDlI5DMOVDhWvQ== stefan@arcturus
"""

################################################################################
# boot process

[[file]]
path    = "/usr/share/holo/files/50-poghril/etc/mkinitcpio.conf.holoscript"
mode    = "0755"
content = """
    #!/bin/bash
    sed 's/^MODULES=.*$/MODULES="xen_blkfront"/'
"""

[[action]]
on     = "setup"
script = "mkinitcpio -p linux"

################################################################################
# filesystem

[[file]]
path    = "/etc/fstab.local"
content = "/dev/xvda  /  ext4  defaults,barrier=0  1  1"

################################################################################
# network interface configuration (the hoster's installer generated netctl
# configs, which I upgraded to systemd-networkd)

[[file]]
path    = "/etc/systemd/network/50-ispone.network"
content = """
    [Match]
    Name=e*

    [Address]
    Address=${POGHRIL_IP4ADDR}/32
    Peer=172.16.147.1/32

    [Network]
    Gateway=172.16.147.1
    DNS=84.38.65.94
    DNS=84.38.66.52
"""
[[symlink]]
path   = "/usr/share/holo/files/50-poghril-vars/etc/systemd/network/50-ispone.network.holoscript"
target = "/my/variables"

[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/systemd-resolved.service"
target = "/usr/lib/systemd/system/systemd-resolved.service"

[[symlink]]
path   = "/usr/share/holo/files/50-poghril/etc/resolv.conf"
target = "/run/systemd/resolve/resolv.conf"

################################################################################
# firewall

[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/ferm.service"
target = "/usr/lib/systemd/system/ferm.service"

[[file]]
path    = "/usr/share/holo/files/50-bethselamin/etc/ferm.conf"
content = """
    table filter {
        chain INPUT {
            policy DROP;

            # connection tracking
            mod state state INVALID DROP;
            mod state state (ESTABLISHED RELATED) ACCEPT;

            # allow local connections
            interface lo ACCEPT;

            # respond to ping
            proto icmp icmp-type echo-request ACCEPT;

            # allow SSH, HTTP, HTTPS
            proto tcp dport ssh ACCEPT;
            proto tcp dport http ACCEPT;
            proto tcp dport https ACCEPT;

            # the rest is dropped by the above policy
        }

        # outgoing connections are not limited
        chain OUTPUT policy ACCEPT;

        # this is not a router
        chain FORWARD policy DROP;
    }
"""
