[package]
name        = "hologram-dev-tools"
version     = "1.3.6"
description = "hologram: compilers and development tools"

requires = [
    "hologram-dev-tools-minimal",
    "apitrace",
    "arch-install-scripts",
    "cargo",
    "cmake",
    "docker",                 # NOTE: not enabled (as in "systemctl enable") by default to avoid confusion with networking and stuff
    "doxygen",
    "gdb",
    "hugo",
    "perl-ipc-system-simple", # required for build_package.pl in this repo
    "pkgbuild-introspection",
    "pygmentize",             # optional dependency for Hugo
    "rust",
    "sloccount",
    "valgrind",
]

[[user]]
name   = "stefan"
groups = ["docker"]
